version: 0.2

phases:
    build:
        commands:
          - echo Entered the build phase
            - mvn clean package
    post_build:
        commands:
            - echo build phase completed
artifacts:
  files:
    - target/order-cicd-service.jar
  discard-paths: yes